/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


  class JSI_EXPORT NativeQuackCxxSpecJSI : public TurboModule {
protected:
  NativeQuackCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
  virtual jsi::String hello(jsi::Runtime &rt) = 0;

};

template <typename T>
class JSI_EXPORT NativeQuackCxxSpec : public TurboModule {
public:
  jsi::Value get(jsi::Runtime &rt, const jsi::PropNameID &propName) override {
    return delegate_.get(rt, propName);
  }

  static constexpr std::string_view kModuleName = "Quack";

protected:
  NativeQuackCxxSpec(std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule(std::string{NativeQuackCxxSpec::kModuleName}, jsInvoker),
      delegate_(reinterpret_cast<T*>(this), jsInvoker) {}


private:
  class Delegate : public NativeQuackCxxSpecJSI {
  public:
    Delegate(T *instance, std::shared_ptr<CallInvoker> jsInvoker) :
      NativeQuackCxxSpecJSI(std::move(jsInvoker)), instance_(instance) {

    }

    jsi::String hello(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::hello) == 1,
          "Expected hello(...) to have 1 parameters");

      return bridging::callFromJs<jsi::String>(
          rt, &T::hello, jsInvoker_, instance_);
    }

  private:
    friend class NativeQuackCxxSpec;
    T *instance_;
  };

  Delegate delegate_;
};

} // namespace facebook::react
