/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RNQuackSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeQuackCxxSpecJSI_hello(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeQuackCxxSpecJSI *>(&turboModule)->hello(
    rt
  );
}

NativeQuackCxxSpecJSI::NativeQuackCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("Quack", jsInvoker) {
  methodMap_["hello"] = MethodMetadata {0, __hostFunction_NativeQuackCxxSpecJSI_hello};
}


} // namespace facebook::react
